import random
i=int(input("Введите количество анализов:"))

while i>0:
    volume = random.randint(50, 200)
    color = ["светло-жёлтая", "желтая","желтая","желтая","желтая","желтая","желтая","желтая","желтая","светло-жёлтая","светло-жёлтая","светло-жёлтая","светло-жёлтая","светло-жёлтая", "тёмно-желтая"]
    random.shuffle(color)
    reaction = random.randint(5, 8)
    relweight = random.randint(1005, 1025)
    wbc = ["0-1", "1-2", "2-3", "един."]
    random.shuffle(wbc)
    rbc = ["0-1", "1-2", "един."]
    random.shuffle(rbc)
    epit = ["0-1", "1-2", "2-3", "3-5", "един."]
    random.shuffle(epit)
    print ("Доставленное количество:", volume)
    print ("Цвет:", color.pop())
    print ("Прозрачность: прозрачная")
    print ("Осадок: нет")
    print ("Реакция:", reaction)
    print ("Удельный вес:", relweight)
    print ("Белок:     отриц.")
    print ("Сахар:     отриц.")
    print ("Уробилин:  отриц.")
    print ("Желч.пигм.:отриц.")
    print ("Лейкоциты: ", wbc.pop())
    print ("Эритроциты:", rbc.pop())
    print ("Цилиндры:   отриц.")
    print ("Эпителий:  ", epit.pop())
    print ("Слизь:     отриц.")
    print ("Соли:      отриц.")
    print ("=======================")
    
    #w1=str(("Доставленное количество:", volume))
   
    #with open('log.txt',"at") as logfile:
    #    logfile.write(w1+'\n')
    d1=str(volume)
    d2=str(color.pop())
    d3=str(reaction)
    d4=str(relweight)
    d5=str(wbc.pop())
    d6=str(rbc.pop())
    d7=str(epit.pop())
    f=open("log.txt", "at" )
    f.write("Дост. кол-во:  "+d1)
    f.write("\n")
    f.write("Цвет:          "+d2)
    f.write("\n")
    f.write("Осадок:        нет")
    f.write("\n")
    f.write("Реакция:      "+d3)
    f.write("\n")
    f.write("Удельный вес: "+d4)
    f.write("\n")
    f.write("Белок:         отриц.")
    f.write("\n")
    f.write("Сахар:         отриц.")
    f.write("\n")
    f.write("Уробилин:    отриц.")
    f.write("\n")
    f.write("Желч.пигм.:  отриц.")
    f.write("\n")
    f.write("Лейкоциты:    "+d5)
    
    f.write("\n")
    f.write("Эритроциты:  "+d6)
    f.write("\n")
    f.write("Цилиндры:    отриц.")
    f.write("\n")
    f.write("Эпителий:     "+d7)
    f.write("\n")
    f.write ("Слизь:          отриц.")
    f.write("\n")
    f.write ("Соли:           отриц.")
    f.write("\n")
    f.write ("=======================")
    f.write("\n")
    f.close()
    i=i-1
input("Press Enter to quit")
